// List of effects

export const ERROR_HANDLER = 'ERROR_HANDLER';

export const API_FACEBOOK_DO_LOGIN_PROMPT = 'API_FACEBOOK_DO_LOGIN_PROMPT';
export const API_FACEBOOK_AUTH = 'API_FACEBOOK_AUTH';
export const API_AUTH_WHATWINE = 'API_AUTH_WHATWINE';
export const API_FETCH_MORE_RESTAURANTS = 'API_FETCH_MORE_RESTAURANTS';

export const API_FETCH_RESTAURANTS = 'API_FETCH_RESTAURANTS';
export const API_FETCH_DISHES = 'API_FETCH_DISHES';
export const API_FETCH_DISH_ALIASES = 'API_FETCH_DISH_ALIASES';
export const API_FETCH_WINES = 'API_FETCH_WINES';

export const ROUTER_BOOTSTRAP_ROUTING = 'ROUTER_BOOTSTRAP_ROUTING';
export const ROUTER_CHANGE_URL = 'ROUTER_CHANGE_URL';
export const ROUTER_GO_BACK = 'ROUTER_GO_BACK';

export const GEOLOC_GET_POSITION = 'GEOLOC_GET_POSTION';
